{% set name = "mockredispy" %}
{% set version = "2.9.3" %}
{% set build = 1 %}
{% set hash = "3bacb3f03f91d62b3b0214479716108211e164357dba32959abbfaf4a28e06f0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://github.com/locationlabs/mockredis/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - nose

  run:
    - python
    - setuptools

test:
  imports:
    - mockredis

about:
  home: https://www.github.com/locationlabs/mockredis
  summary: 'Mock for redis-py'
  license: Apache2
  license_file: LICENSE
  license_family: APACHE
  dev_url: https://www.github.com/locationlabs/mockredis
  doc_url: https://www.github.com/locationlabs/mockredis

extra:
  recipe-maintainers:
    - kwilcox
