travis:
  secure:
    BINSTAR_TOKEN: nd+iBv3IeeSVZqRGbQm5kecBU6ztb6x45JPcOP21x8vWk7OSb8E8tMKCDhnQ559KzIsivQxA1wNxCnOL6F37D6UYCtv0VWCjt8BwK8cYv4SueHwnKbosPVhxSDggzvlg+unYc5xfBQfIOvJfNpoXDbzqSIUGU564XoLO72Pf7BrQYIHPqsi4FQobZeq3yUbowtN/X9gXVDGt1gN73wx05ynKa7WifdC/dCWBZlpsjyceYRTKN88VArD3fGdz1BNVGVoQ58MoaGo8D5WBbFTaQYi+Ya9EFxtzuw7YPo8tm4OUaUEzeHIDiI2/kFCL8O0MXTvJl+4dDcgcG1zj6l1a+FpS1jZSxvQEf1LzT/N10JKuPfFeqkJoef+E7KiNc0P2V6wdGYLIZ2KSD6gH03iZhBtrOy02W+pXQaJ91KB/oHpWnC0eADbatFCy2LqclceKKCGI7PvsyY+LbITThfklWITSW7K0+DC+nqelorWNycQD8fx4xZJfUsfiPlzxyjT1I/Z9QxDOXCgvBQwXpaKTAGIf/vxTCy9yLOvn/oCYjWkJypWqejQ1v+jlA788oTSDwzVLxguQ9dBuOnIumISPq7q9CHJiE507Ju5RsrYO/MrJ45OPCErXbBJW0v0WaXRgupnyaaamZ3Fa/5gcJsPoKzXihe2rQGQSKZjI+HZNwVo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
