travis:
  secure:
    BINSTAR_TOKEN: h8s6Hu0q3uDzcaY3DUB3dc1PjWZYFpQpnbAqrKnPQ0IiBV3tzrgrqIm9VeYH7tYE5NtNy3JgMWjkz6OypXeaXVNQqyKDCgBqMsDCu+eHXSZ/UtRhawgGRDJ2r6aflp0hS22LF2dgFXuu2RRA+XVR5Od9iC5KIdqvLIaJDugmrfW2E1xs4JAhlAcdj3onrfqYdQRiicVxO5s1viAyBpd5nYnEoX/cBiLPWlFFk//Xe/mh+T4Eof91ldJooEiDWRdUsFIRIJa9AzZKGrKoNmzDqI1/8G5v/04IcBUmdelELKON0saoBndOtaIatrYNUaiiQFZXaI+zfzH2IABA1GIlkGURuEDaszES8EoBWO9i2t3bkP5K+yN2Fo9eIr9NHJcx62mmMiR+x70aFA8wqN7uqUhDpX4aYXEJxHII6tEat+DuqeGXkcJXP5KOvQ8DL+w8ceKYHdx5ykY1KYFzkuM+pbTBsO1dvfwNTbM42Y/DzronpLyKkTl9N7rD5xexv6OUOkdIoynn2J4CcYmFYqLMxBrES3NDq4PVNpMoHQ7S+yVuQhKqGyD8fhYy4vD3WgOo3qTxsCFoQBe/qoXtMNc1uv5ku1GcipgZB0TRs464tJ9s6SkaUHTOcMqjM04GkuT+QrTW3JcmmexWEnPS4afHXKg+BGlgQF1t8Bdn5Lp6OZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
